In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [12]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
np.random.rand(5)

array([ 0.39392641,  0.37729234,  0.30797177,  0.64056766,  0.992664  ])

In [14]:
np.random.rand(5,5)

array([[ 0.35647953,  0.58220856,  0.00768033,  0.31452907,  0.84462267],
       [ 0.01619557,  0.91127941,  0.71097945,  0.39984515,  0.29833449],
       [ 0.63716236,  0.78336223,  0.92081237,  0.65127567,  0.31539208],
       [ 0.52422845,  0.43283897,  0.71173704,  0.20670576,  0.61301198],
       [ 0.65344401,  0.34745656,  0.88370143,  0.39953335,  0.05689927]])

In [15]:
np.random.rand(2)

array([ 0.48538458,  0.40991503])

In [17]:
np.random.randint(1,100,10)

array([99, 94, 57, 33, 11, 28, 73, 90, 91, 25])

In [18]:
arr=np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr=np.random.randint(0,50,10)

In [21]:
ranarr

array([47, 36,  1, 13,  5,  2, 29, 36, 25, 25])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr

array([47, 36,  1, 13,  5,  2, 29, 36, 25, 25])

In [26]:
ranarr.max()

47

In [27]:
ranarr.min()

1

In [28]:
ranarr.argmax()

0

In [29]:
ranarr.argmin()

2

In [30]:
arr.shape

(25,)

In [32]:
arr=arr.reshape(5,5)

In [34]:
arr.shape

(5, 5)

In [35]:
from numpy.random import randint

In [36]:
randint(2,10)

4

In [39]:
arr=np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5]=100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr=np.arange(11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_array=arr[0:6]

In [51]:
slice_array

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_array[:]=99

In [54]:
slice_array

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy=arr.copy()

In [57]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy[:]=100

In [60]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[1,2]

30

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr=np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr=arr>5

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr<3]

array([1, 2])

In [77]:
arr_2d=np.arange(50).reshape(5,10)

In [80]:
arr_2d[1:3,2:5]

array([[12, 13, 14],
       [22, 23, 24]])

In [81]:
arr=np.arange(0,11)

In [82]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [87]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [89]:
arr/arr

C:\Anaconda2\envs\python3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [90]:
1/arr

C:\Anaconda2\envs\python3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [91]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [93]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [94]:
np.max(arr)

10

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [96]:
np.log(arr)

C:\Anaconda2\envs\python3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])